-- CI fixture: parent de_* tables only (schema, empty).
-- GENERATED by ci/fixtures/slim_de_dump.py from a prod pg_dump.
-- Do not hand-edit; regenerate per ci/fixtures/README.md.
SET client_min_messages = warning;

CREATE TABLE public.de_equity_ohlcv (
    date date NOT NULL,
    instrument_id uuid NOT NULL,
    symbol character varying(50),
    open numeric(18,4),
    high numeric(18,4),
    low numeric(18,4),
    close numeric(18,4),
    close_adj numeric(18,4),
    open_adj numeric(18,4),
    high_adj numeric(18,4),
    low_adj numeric(18,4),
    volume bigint,
    volume_adj bigint,
    delivery_vol bigint,
    delivery_pct numeric(6,2),
    trades integer,
    data_status character varying(20) DEFAULT 'raw'::character varying NOT NULL,
    source_file_id uuid,
    pipeline_run_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_equity_ohlcv_data_status CHECK (((data_status)::text = ANY (ARRAY[('raw'::character varying)::text, ('validated'::character varying)::text, ('quarantined'::character varying)::text])))
);

CREATE TABLE public.de_index_prices (
    date date NOT NULL,
    index_code character varying(50) NOT NULL,
    open numeric(18,4),
    high numeric(18,4),
    low numeric(18,4),
    close numeric(18,4),
    volume bigint,
    pe_ratio numeric(10,4),
    pb_ratio numeric(10,4),
    div_yield numeric(6,2),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.de_etf_ohlcv (
    date date NOT NULL,
    ticker character varying(30) NOT NULL,
    open numeric(18,4),
    high numeric(18,4),
    low numeric(18,4),
    close numeric(18,4),
    volume bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.de_mf_nav_daily (
    nav_date date NOT NULL,
    mstar_id character varying(20) NOT NULL,
    nav numeric(18,4) NOT NULL,
    nav_adj numeric(18,4),
    nav_change numeric(18,4),
    nav_change_pct numeric(10,4),
    return_1d numeric(10,4),
    return_1w numeric(10,4),
    return_1m numeric(10,4),
    return_3m numeric(10,4),
    return_6m numeric(10,4),
    return_1y numeric(10,4),
    return_3y numeric(10,4),
    return_5y numeric(10,4),
    return_10y numeric(10,4),
    nav_52wk_high numeric(18,4),
    nav_52wk_low numeric(18,4),
    data_status character varying(20) DEFAULT 'raw'::character varying NOT NULL,
    source_file_id uuid,
    pipeline_run_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_mf_nav_data_status CHECK (((data_status)::text = ANY (ARRAY[('raw'::character varying)::text, ('validated'::character varying)::text, ('quarantined'::character varying)::text]))),
    CONSTRAINT chk_mf_nav_positive CHECK ((nav > (0)::numeric))
);

CREATE TABLE public.de_global_prices (
    date date NOT NULL,
    ticker character varying(20) NOT NULL,
    open numeric(18,4),
    high numeric(18,4),
    low numeric(18,4),
    close numeric(18,4),
    volume bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.de_adjustment_factors_daily (
    instrument_id uuid NOT NULL,
    date date NOT NULL,
    cumulative_factor numeric(18,8) DEFAULT 1.0 NOT NULL,
    last_action_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.de_contributors (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    role character varying(20) NOT NULL,
    is_admin boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_contributor_role CHECK (((role)::text = ANY (ARRAY[('admin'::character varying)::text, ('analyst'::character varying)::text, ('pipeline'::character varying)::text, ('viewer'::character varying)::text, ('external'::character varying)::text])))
);

CREATE TABLE public.de_corporate_actions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    instrument_id uuid NOT NULL,
    ex_date date NOT NULL,
    action_type character varying(20) NOT NULL,
    dividend_type character varying(10),
    ratio_from numeric(18,8),
    ratio_to numeric(18,8),
    cash_value numeric(18,4),
    new_instrument_id uuid,
    adj_factor numeric(18,8),
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_corp_action_type CHECK (((action_type)::text = ANY (ARRAY[('dividend'::character varying)::text, ('split'::character varying)::text, ('bonus'::character varying)::text, ('rights'::character varying)::text, ('merger'::character varying)::text, ('demerger'::character varying)::text, ('buyback'::character varying)::text, ('delisting'::character varying)::text, ('suspension'::character varying)::text, ('name_change'::character varying)::text, ('isin_change'::character varying)::text, ('other'::character varying)::text]))),
    CONSTRAINT chk_corp_dividend_type CHECK ((((dividend_type)::text = ANY (ARRAY[('interim'::character varying)::text, ('final'::character varying)::text, ('special'::character varying)::text, ('none'::character varying)::text])) OR (dividend_type IS NULL)))
);

CREATE TABLE public.de_cron_run (
    id integer NOT NULL,
    schedule_name character varying(100) NOT NULL,
    business_date date,
    started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    duration_seconds numeric(10,3),
    http_code integer,
    curl_exit_code integer,
    status character varying(20) NOT NULL,
    error_body text,
    host character varying(100)
);

CREATE TABLE public.de_data_anomalies (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    pipeline_name character varying(100) NOT NULL,
    business_date date,
    entity_type character varying(20) NOT NULL,
    instrument_id uuid,
    mstar_id character varying(20),
    ticker character varying(20),
    anomaly_type character varying(30) NOT NULL,
    severity character varying(10) NOT NULL,
    expected_range character varying(200),
    actual_value character varying(200),
    is_resolved boolean DEFAULT false NOT NULL,
    resolved_by character varying(100),
    resolved_at timestamp with time zone,
    resolution_note text,
    detected_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_data_anomaly_entity_ref_consistency CHECK (((((entity_type)::text = 'equity'::text) AND (instrument_id IS NOT NULL)) OR (((entity_type)::text = 'mf'::text) AND (mstar_id IS NOT NULL)) OR (((entity_type)::text = ANY (ARRAY[('macro'::character varying)::text, ('flow'::character varying)::text])) AND (ticker IS NOT NULL)) OR (((entity_type)::text = 'index'::text) AND ((ticker IS NOT NULL) OR (instrument_id IS NOT NULL))))),
    CONSTRAINT chk_data_anomaly_entity_type CHECK (((entity_type)::text = ANY (ARRAY[('equity'::character varying)::text, ('mf'::character varying)::text, ('index'::character varying)::text, ('macro'::character varying)::text, ('flow'::character varying)::text]))),
    CONSTRAINT chk_data_anomaly_severity CHECK (((severity)::text = ANY (ARRAY[('low'::character varying)::text, ('medium'::character varying)::text, ('high'::character varying)::text, ('critical'::character varying)::text]))),
    CONSTRAINT chk_data_anomaly_type CHECK (((anomaly_type)::text = ANY (ARRAY[('price_spike'::character varying)::text, ('price_gap'::character varying)::text, ('zero_volume'::character varying)::text, ('missing_data'::character varying)::text, ('duplicate'::character varying)::text, ('negative_value'::character varying)::text, ('stale_data'::character varying)::text, ('nav_deviation'::character varying)::text, ('dividend_anomaly'::character varying)::text, ('split_mismatch'::character varying)::text, ('invalid_ratio'::character varying)::text, ('other'::character varying)::text])))
);

CREATE TABLE public.de_etf_holdings (
    ticker character varying(30) NOT NULL,
    instrument_id uuid NOT NULL,
    weight numeric(8,6) NOT NULL,
    as_of_date date NOT NULL,
    last_disclosed_date date NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_etf_holdings_weight_range CHECK (((weight >= (0)::numeric) AND (weight <= (1)::numeric)))
);

CREATE TABLE public.de_etf_master (
    ticker character varying(30) NOT NULL,
    name character varying(200) NOT NULL,
    exchange character varying(20) NOT NULL,
    country character varying(10) DEFAULT 'US'::character varying NOT NULL,
    currency character varying(5),
    sector character varying(100),
    asset_class character varying(50) DEFAULT 'equity'::character varying,
    category character varying(100),
    benchmark character varying(50),
    expense_ratio numeric(6,4),
    inception_date date,
    is_active boolean DEFAULT true NOT NULL,
    source character varying(20) DEFAULT 'stooq'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    mstar_id character varying(20)
);

CREATE TABLE public.de_global_instrument_master (
    ticker character varying(20) NOT NULL,
    name character varying(200) NOT NULL,
    instrument_type character varying(10) NOT NULL,
    exchange character varying(20),
    currency character varying(5),
    country character varying(50),
    category character varying(100),
    source character varying(50),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_global_instrument_type CHECK (((instrument_type)::text = ANY (ARRAY[('index'::character varying)::text, ('etf'::character varying)::text])))
);

CREATE TABLE public.de_healing_log (
    id integer NOT NULL,
    date date NOT NULL,
    stream_id character varying(100) NOT NULL,
    pipeline_triggered character varying(100) NOT NULL,
    action character varying(50) NOT NULL,
    result character varying(50) NOT NULL,
    retries integer DEFAULT 0 NOT NULL,
    error_detail text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.de_index_constituents (
    index_code character varying(50) NOT NULL,
    instrument_id uuid NOT NULL,
    effective_from date NOT NULL,
    weight_pct numeric(6,4),
    effective_to date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.de_index_master (
    index_code character varying(50) NOT NULL,
    index_name character varying(200) NOT NULL,
    category character varying(20) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_index_category CHECK (((category)::text = ANY (ARRAY[('broad'::character varying)::text, ('sectoral'::character varying)::text, ('thematic'::character varying)::text, ('strategy'::character varying)::text])))
);

CREATE TABLE public.de_instrument (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    current_symbol character varying(50) NOT NULL,
    isin character varying(12),
    company_name character varying(500),
    exchange character varying(10),
    series character varying(10),
    sector character varying(200),
    industry character varying(200),
    nifty_50 boolean DEFAULT false NOT NULL,
    nifty_200 boolean DEFAULT false NOT NULL,
    nifty_500 boolean DEFAULT false NOT NULL,
    listing_date date,
    bse_symbol character varying(50),
    is_active boolean DEFAULT true NOT NULL,
    is_suspended boolean DEFAULT false NOT NULL,
    suspended_from date,
    delisted_on date,
    is_tradeable boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    symbol character varying(50) GENERATED ALWAYS AS (current_symbol) STORED,
    bse_scripcode character varying(20)
);

CREATE TABLE public.de_mf_holdings (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    mstar_id character varying(20) NOT NULL,
    as_of_date date NOT NULL,
    holding_name character varying(500),
    isin character varying(12),
    instrument_id uuid,
    weight_pct numeric(6,4),
    shares_held bigint,
    market_value numeric(18,4),
    sector_code character varying(50),
    is_mapped boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.de_mf_lifecycle (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    mstar_id character varying(20) NOT NULL,
    event_type character varying(30) NOT NULL,
    event_date date NOT NULL,
    old_value text,
    new_value text,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_mf_lifecycle_event_type CHECK (((event_type)::text = ANY (ARRAY[('launch'::character varying)::text, ('merge'::character varying)::text, ('name_change'::character varying)::text, ('category_change'::character varying)::text, ('amc_change'::character varying)::text, ('closure'::character varying)::text, ('benchmark_change'::character varying)::text, ('reopen'::character varying)::text])))
);

CREATE TABLE public.de_mf_master (
    mstar_id character varying(20) NOT NULL,
    amfi_code character varying(20),
    isin character varying(12),
    fund_name character varying(500) NOT NULL,
    amc_name character varying(200),
    category_name character varying(200),
    broad_category character varying(100),
    is_index_fund boolean DEFAULT false NOT NULL,
    is_etf boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    inception_date date,
    closure_date date,
    merged_into_mstar_id character varying(20),
    primary_benchmark character varying(100),
    expense_ratio numeric(6,4),
    investment_strategy text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    purchase_mode integer,
    CONSTRAINT chk_mf_no_self_merge CHECK (((merged_into_mstar_id IS NULL) OR ((merged_into_mstar_id)::text <> (mstar_id)::text)))
);

CREATE TABLE public.de_pipeline_log (
    id integer NOT NULL,
    pipeline_name character varying(100) NOT NULL,
    business_date date,
    run_number integer DEFAULT 1 NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    rows_processed bigint,
    rows_failed bigint,
    source_date date,
    source_rowcount bigint,
    source_checksum character varying(64),
    error_detail text,
    track_status jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_pipeline_log_status CHECK (((status)::text = ANY (ARRAY[('pending'::character varying)::text, ('running'::character varying)::text, ('success'::character varying)::text, ('partial'::character varying)::text, ('failed'::character varying)::text, ('skipped'::character varying)::text])))
);

CREATE TABLE public.de_sector_mapping (
    jip_sector_name character varying(50) NOT NULL,
    primary_nse_index character varying(50) NOT NULL,
    secondary_nse_indices text[],
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.de_source_files (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    source_name character varying(100) NOT NULL,
    file_name character varying(500) NOT NULL,
    file_date date,
    checksum character varying(64),
    file_size_bytes bigint,
    row_count bigint,
    format_version character varying(50),
    ingested_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.de_system_flags (
    key character varying(50) NOT NULL,
    value boolean DEFAULT true NOT NULL,
    updated_by character varying(100),
    updated_at timestamp with time zone,
    reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.de_trading_calendar (
    date date NOT NULL,
    is_trading boolean NOT NULL,
    exchange character varying(10) DEFAULT 'NSE'::character varying NOT NULL,
    notes character varying(200),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

