#!/usr/bin/env python3
"""Slim a raw `pg_dump --schema-only` of the de_* tables down to what CI needs.

The DE pipeline's prod schema carries partition children, indexes, FK
constraints, sequences, and RLS policies — none of which a fresh CI database
needs (and several of which would *fail* there: RLS policies reference prod-only
roles, FKs may target non-de_ tables). atlas migrations only need the **parent**
de_* tables to exist with their columns, so the MV/index DDL they run can
resolve against them.

This keeps exactly that: each top-level parent table's column definition,
flattened to a plain (non-partitioned) empty table. Everything else is dropped.

Usage (see README.md):
    docker run --rm postgres:17 pg_dump "$PSQL_URL" --schema-only \
        --no-owner --no-privileges --no-comments -t 'public.de_*' \
      | python ci/fixtures/slim_de_dump.py > ci/fixtures/external_de_tables.sql
"""

from __future__ import annotations

import re
import sys

HEADER_RE = re.compile(r"^-- Name: (?P<name>[^;]+); Type: (?P<type>[A-Z ]+);")


def parse_objects(text: str) -> list[tuple[str, str, str]]:
    """Split a pg_dump into (name, type, body) tuples keyed by its -- Name headers."""
    objects: list[tuple[str, str, str]] = []
    name = ""
    type_ = ""
    buf: list[str] = []
    for line in text.splitlines():
        m = HEADER_RE.match(line)
        if m:
            if name:
                objects.append((name, type_, "\n".join(buf).strip()))
            name, type_ = m.group("name"), m.group("type").strip()
            buf = []
        elif name:
            buf.append(line)
    if name:
        objects.append((name, type_, "\n".join(buf).strip()))
    return objects


def flatten_table(create_sql: str) -> str:
    """Turn a partitioned parent CREATE TABLE into a plain empty table.

    - Drop the trailing ``PARTITION BY ...`` clause (no partitions in CI).
    - Drop ``DEFAULT nextval(...)`` (the owning sequences are not emitted).
    """
    # Strip a CREATE TABLE statement at the first standalone CREATE TABLE.
    start = create_sql.find("CREATE TABLE ")
    if start == -1:
        return ""
    stmt = create_sql[start:]
    # Cut at the statement terminator.
    end = stmt.find(";")
    stmt = stmt[: end + 1] if end != -1 else stmt
    # ")\nPARTITION BY RANGE (date);" -> ");"
    stmt = re.sub(r"\)\s*PARTITION BY[^;]*;", ");", stmt)
    # Remove per-column DEFAULT nextval(...) (sequences are dropped).
    stmt = re.sub(r"\s+DEFAULT nextval\([^)]*\)", "", stmt)
    return stmt.strip()


def main() -> int:
    text = sys.stdin.read()
    objects = parse_objects(text)
    children = {name for name, type_, _ in objects if type_ == "TABLE ATTACH"}

    tables: list[str] = []
    for name, type_, body in objects:
        if type_ != "TABLE" or name in children:
            continue
        stmt = flatten_table(body)
        if stmt:
            tables.append(stmt)

    out = [
        "-- CI fixture: parent de_* tables only (schema, empty).",
        "-- GENERATED by ci/fixtures/slim_de_dump.py from a prod pg_dump.",
        "-- Do not hand-edit; regenerate per ci/fixtures/README.md.",
        "SET client_min_messages = warning;",
        "",
    ]
    out.extend(s + "\n" for s in tables)
    sys.stdout.write("\n".join(out) + "\n")
    sys.stderr.write(f"slim_de_dump: kept {len(tables)} parent tables\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
