"""SP04 Stage 4a: rolling IC monitor + weight proposals.

- atlas_signal_ic_rolling: per (tier, signal, lookback_window, as_of_date)
  point-in-time IC measurement against forward returns. Audit-only — keeps
  a full history so candidate_generator can reason over recent windows.
- atlas_weight_proposals: candidate weight sets generated by the
  optimization loop. Status tracks the approval workflow:
  pending → approved | rejected | snoozed | superseded.

Revision ID: 040
Revises: 039
Create Date: 2026-05-12
"""

import sqlalchemy as sa
from alembic import op

revision = "040"
down_revision = "039"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        sa.text("""
        CREATE TABLE IF NOT EXISTS atlas.atlas_signal_ic_rolling (
            id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            as_of_date      DATE NOT NULL,
            tier            VARCHAR(32) NOT NULL,
            signal_name     VARCHAR(64) NOT NULL,
            lookback_window INTEGER NOT NULL,
            forward_horizon INTEGER NOT NULL,
            n_observations  INTEGER NOT NULL,
            ic              NUMERIC(8, 6) NOT NULL,
            t_stat          NUMERIC(8, 4),
            created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT chk_ic_rolling_tier CHECK (tier IN (
                'tier_1_megacap','tier_2_largecap','tier_3_uppermid',
                'tier_4_lowermid','tier_5_smallcap'
            )),
            CONSTRAINT chk_ic_rolling_window CHECK (lookback_window > 0),
            CONSTRAINT chk_ic_rolling_horizon CHECK (forward_horizon > 0),
            CONSTRAINT chk_ic_rolling_n CHECK (n_observations >= 0)
        )
        """)
    )
    op.execute(
        sa.text("""
        CREATE UNIQUE INDEX IF NOT EXISTS uq_ic_rolling_keys
        ON atlas.atlas_signal_ic_rolling
        (as_of_date, tier, signal_name, lookback_window, forward_horizon)
        """)
    )
    op.execute(
        sa.text("""
        CREATE INDEX IF NOT EXISTS idx_ic_rolling_recent
        ON atlas.atlas_signal_ic_rolling (tier, signal_name, as_of_date DESC)
        """)
    )

    op.execute(
        sa.text("""
        CREATE TABLE IF NOT EXISTS atlas.atlas_weight_proposals (
            id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            tier                VARCHAR(32) NOT NULL,
            regime              VARCHAR(16) NOT NULL DEFAULT 'all',
            proposed_weights    JSONB NOT NULL,
            current_weights     JSONB NOT NULL,
            proposed_holdout_ic NUMERIC(8, 6),
            current_holdout_ic  NUMERIC(8, 6),
            ic_delta            NUMERIC(8, 6),
            rationale           TEXT,
            generator_version   VARCHAR(64) NOT NULL DEFAULT 'sp04-stage4a-v1',
            status              VARCHAR(16) NOT NULL DEFAULT 'pending',
            reviewed_by         VARCHAR(64),
            reviewed_at         TIMESTAMPTZ,
            review_notes        TEXT,
            applied_weights     JSONB,
            applied_at          TIMESTAMPTZ,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT chk_prop_tier CHECK (tier IN (
                'tier_1_megacap','tier_2_largecap','tier_3_uppermid',
                'tier_4_lowermid','tier_5_smallcap'
            )),
            CONSTRAINT chk_prop_regime CHECK (regime IN (
                'Risk-On','Constructive','Cautious','Risk-Off','all'
            )),
            CONSTRAINT chk_prop_status CHECK (status IN (
                'pending','approved','rejected','snoozed','superseded'
            ))
        )
        """)
    )
    op.execute(
        sa.text("""
        CREATE INDEX IF NOT EXISTS idx_proposals_status_tier
        ON atlas.atlas_weight_proposals (status, tier, created_at DESC)
        """)
    )
    op.execute(
        sa.text("""
        CREATE UNIQUE INDEX IF NOT EXISTS uq_proposals_active_per_tier
        ON atlas.atlas_weight_proposals (tier, regime)
        WHERE status = 'pending'
        """)
    )


def downgrade() -> None:
    op.execute(sa.text("DROP TABLE IF EXISTS atlas.atlas_weight_proposals"))
    op.execute(sa.text("DROP TABLE IF EXISTS atlas.atlas_signal_ic_rolling"))
