"""Seed S&P 500 universe and align stock tables with full state machinery.

Changes:
- us_atlas.atlas_stock_states_daily: add rs_state, compute_run_id
- us_atlas.atlas_stock_metrics_daily: add effort_ratio_63; make instrument_id nullable
- us_atlas.atlas_universe_stocks: seed ~500 S&P 500 tickers with GICS sectors + Large tier
- Seed weinstein/history/liquidity thresholds that states.py needs (not seeded in 055)

Revision ID: 060
Revises: 059
Create Date: 2026-05-13
"""

from alembic import op

revision = "060"
down_revision = "059"
branch_labels = None
depends_on = None


# ---------------------------------------------------------------------------
# S&P 500 universe: (ticker, gics_sector)
# Tickers lowercased; '.' → '-' per stooq convention (same as get_sp500_tickers).
# All marked tier='Large' — S&P 500 is a large-cap index.
# ---------------------------------------------------------------------------
_SP500 = [
    # Information Technology
    ("aapl", "Information Technology"),
    ("msft", "Information Technology"),
    ("nvda", "Information Technology"),
    ("avgo", "Information Technology"),
    ("orcl", "Information Technology"),
    ("crm", "Information Technology"),
    ("acn", "Information Technology"),
    ("csco", "Information Technology"),
    ("ibm", "Information Technology"),
    ("txn", "Information Technology"),
    ("qcom", "Information Technology"),
    ("amd", "Information Technology"),
    ("now", "Information Technology"),
    ("intu", "Information Technology"),
    ("amat", "Information Technology"),
    ("mu", "Information Technology"),
    ("lrcx", "Information Technology"),
    ("klac", "Information Technology"),
    ("panw", "Information Technology"),
    ("cdns", "Information Technology"),
    ("ftnt", "Information Technology"),
    ("snps", "Information Technology"),
    ("anet", "Information Technology"),
    ("msi", "Information Technology"),
    ("adi", "Information Technology"),
    ("mchp", "Information Technology"),
    ("intc", "Information Technology"),
    ("hpq", "Information Technology"),
    ("hpe", "Information Technology"),
    ("wdc", "Information Technology"),
    ("stx", "Information Technology"),
    ("jnpr", "Information Technology"),
    ("ntap", "Information Technology"),
    ("tel", "Information Technology"),
    ("aph", "Information Technology"),
    ("glw", "Information Technology"),
    ("keys", "Information Technology"),
    ("trmb", "Information Technology"),
    ("it", "Information Technology"),
    ("ldos", "Information Technology"),
    ("ctsh", "Information Technology"),
    ("dxc", "Information Technology"),
    ("gddy", "Information Technology"),
    ("akam", "Information Technology"),
    ("cdw", "Information Technology"),
    ("ptc", "Information Technology"),
    ("zbra", "Information Technology"),
    ("tdy", "Information Technology"),
    ("ter", "Information Technology"),
    ("enph", "Information Technology"),
    ("fslr", "Information Technology"),
    ("gen", "Information Technology"),
    ("rop", "Information Technology"),
    ("vrsn", "Information Technology"),
    ("ffiv", "Information Technology"),
    ("anss", "Information Technology"),
    ("br", "Information Technology"),
    ("mpwr", "Information Technology"),
    ("swks", "Information Technology"),
    ("qrvo", "Information Technology"),
    ("tyl", "Information Technology"),
    ("jkhy", "Information Technology"),
    ("ttwo", "Information Technology"),
    ("ea", "Information Technology"),
    ("rblx", "Information Technology"),
    ("snap", "Information Technology"),
    # Financials
    ("brk-b", "Financials"),
    ("jpm", "Financials"),
    ("bac", "Financials"),
    ("wfc", "Financials"),
    ("gs", "Financials"),
    ("ms", "Financials"),
    ("c", "Financials"),
    ("axp", "Financials"),
    ("blk", "Financials"),
    ("schw", "Financials"),
    ("cb", "Financials"),
    ("mmc", "Financials"),
    ("pgr", "Financials"),
    ("aon", "Financials"),
    ("ice", "Financials"),
    ("cme", "Financials"),
    ("spgi", "Financials"),
    ("mco", "Financials"),
    ("tfc", "Financials"),
    ("usb", "Financials"),
    ("pnc", "Financials"),
    ("cof", "Financials"),
    ("aig", "Financials"),
    ("all", "Financials"),
    ("met", "Financials"),
    ("pru", "Financials"),
    ("afl", "Financials"),
    ("hig", "Financials"),
    ("cinf", "Financials"),
    ("gl", "Financials"),
    ("eg", "Financials"),
    ("rnr", "Financials"),
    ("re", "Financials"),
    ("wrb", "Financials"),
    ("acgl", "Financials"),
    ("bx", "Financials"),
    ("kkr", "Financials"),
    ("apo", "Financials"),
    ("cg", "Financials"),
    ("ares", "Financials"),
    ("fis", "Financials"),
    ("fi", "Financials"),
    ("pypl", "Financials"),
    ("v", "Financials"),
    ("ma", "Financials"),
    ("amp", "Financials"),
    ("ivz", "Financials"),
    ("ben", "Financials"),
    ("trow", "Financials"),
    ("ntrs", "Financials"),
    ("stt", "Financials"),
    ("bk", "Financials"),
    ("cfg", "Financials"),
    ("hban", "Financials"),
    ("rf", "Financials"),
    ("key", "Financials"),
    ("fitb", "Financials"),
    ("mtb", "Financials"),
    ("zion", "Financials"),
    ("cma", "Financials"),
    ("fhn", "Financials"),
    ("snv", "Financials"),
    ("wal", "Financials"),
    ("wbs", "Financials"),
    ("boh", "Financials"),
    ("ewbc", "Financials"),
    ("wtfc", "Financials"),
    # Health Care
    ("unh", "Health Care"),
    ("jnj", "Health Care"),
    ("lly", "Health Care"),
    ("abbv", "Health Care"),
    ("mrk", "Health Care"),
    ("tmo", "Health Care"),
    ("abt", "Health Care"),
    ("amgn", "Health Care"),
    ("isrg", "Health Care"),
    ("bsx", "Health Care"),
    ("syk", "Health Care"),
    ("elv", "Health Care"),
    ("ci", "Health Care"),
    ("cvs", "Health Care"),
    ("mdt", "Health Care"),
    ("zbh", "Health Care"),
    ("bax", "Health Care"),
    ("bdx", "Health Care"),
    ("dxcm", "Health Care"),
    ("iqv", "Health Care"),
    ("vrtx", "Health Care"),
    ("regn", "Health Care"),
    ("biib", "Health Care"),
    ("ilmn", "Health Care"),
    ("a", "Health Care"),
    ("mtd", "Health Care"),
    ("holx", "Health Care"),
    ("wat", "Health Care"),
    ("tech", "Health Care"),
    ("rmd", "Health Care"),
    ("ew", "Health Care"),
    ("ste", "Health Care"),
    ("algn", "Health Care"),
    ("coo", "Health Care"),
    ("tfx", "Health Care"),
    ("gehc", "Health Care"),
    ("hum", "Health Care"),
    ("moh", "Health Care"),
    ("cnc", "Health Care"),
    ("hca", "Health Care"),
    ("thc", "Health Care"),
    ("dva", "Health Care"),
    ("pdco", "Health Care"),
    ("hsic", "Health Care"),
    ("veev", "Health Care"),
    ("tdoc", "Health Care"),
    ("bmy", "Health Care"),
    ("pfe", "Health Care"),
    ("gild", "Health Care"),
    ("azn", "Health Care"),
    ("nvs", "Health Care"),
    # Industrials
    ("cat", "Industrials"),
    ("hon", "Industrials"),
    ("ge", "Industrials"),
    ("rtx", "Industrials"),
    ("ups", "Industrials"),
    ("de", "Industrials"),
    ("lmt", "Industrials"),
    ("noc", "Industrials"),
    ("gd", "Industrials"),
    ("ba", "Industrials"),
    ("mmm", "Industrials"),
    ("emr", "Industrials"),
    ("etn", "Industrials"),
    ("ph", "Industrials"),
    ("itw", "Industrials"),
    ("fdx", "Industrials"),
    ("csx", "Industrials"),
    ("unp", "Industrials"),
    ("nsc", "Industrials"),
    ("cni", "Industrials"),
    ("cp", "Industrials"),
    ("ame", "Industrials"),
    ("rok", "Industrials"),
    ("xyl", "Industrials"),
    ("fast", "Industrials"),
    ("gww", "Industrials"),
    ("ndsn", "Industrials"),
    ("ir", "Industrials"),
    ("gnrc", "Industrials"),
    ("aos", "Industrials"),
    ("txt", "Industrials"),
    ("hei", "Industrials"),
    ("lhx", "Industrials"),
    ("saic", "Industrials"),
    ("caci", "Industrials"),
    ("mant", "Industrials"),
    ("wm", "Industrials"),
    ("rsg", "Industrials"),
    ("wcn", "Industrials"),
    ("srcl", "Industrials"),
    ("rbc", "Industrials"),
    ("fls", "Industrials"),
    ("enpro", "Industrials"),
    ("esab", "Industrials"),
    ("expd", "Industrials"),
    ("chrw", "Industrials"),
    ("knx", "Industrials"),
    ("wern", "Industrials"),
    ("arcb", "Industrials"),
    ("gatx", "Industrials"),
    ("al", "Industrials"),
    ("gbx", "Industrials"),
    ("lkq", "Industrials"),
    ("mro", "Industrials"),
    ("vrsk", "Industrials"),
    ("dhr", "Industrials"),
    ("spx", "Industrials"),
    ("grub", "Industrials"),
    ("jci", "Industrials"),
    ("csgp", "Industrials"),
    ("cdre", "Industrials"),
    ("pcar", "Industrials"),
    ("cmi", "Industrials"),
    ("acm", "Industrials"),
    ("pwr", "Industrials"),
    ("mas", "Industrials"),
    ("uri", "Industrials"),
    # Consumer Discretionary
    ("amzn", "Consumer Discretionary"),
    ("tsla", "Consumer Discretionary"),
    ("hd", "Consumer Discretionary"),
    ("mcd", "Consumer Discretionary"),
    ("nke", "Consumer Discretionary"),
    ("sbux", "Consumer Discretionary"),
    ("low", "Consumer Discretionary"),
    ("tgt", "Consumer Discretionary"),
    ("tjx", "Consumer Discretionary"),
    ("rost", "Consumer Discretionary"),
    ("dg", "Consumer Discretionary"),
    ("dltr", "Consumer Discretionary"),
    ("yum", "Consumer Discretionary"),
    ("qsr", "Consumer Discretionary"),
    ("dpz", "Consumer Discretionary"),
    ("cmg", "Consumer Discretionary"),
    ("rcl", "Consumer Discretionary"),
    ("ccl", "Consumer Discretionary"),
    ("mgm", "Consumer Discretionary"),
    ("wynn", "Consumer Discretionary"),
    ("lvs", "Consumer Discretionary"),
    ("nclh", "Consumer Discretionary"),
    ("mar", "Consumer Discretionary"),
    ("hlt", "Consumer Discretionary"),
    ("h", "Consumer Discretionary"),
    ("ihg", "Consumer Discretionary"),
    ("expe", "Consumer Discretionary"),
    ("bkng", "Consumer Discretionary"),
    ("abnb", "Consumer Discretionary"),
    ("etsy", "Consumer Discretionary"),
    ("ebay", "Consumer Discretionary"),
    ("vfc", "Consumer Discretionary"),
    ("pvh", "Consumer Discretionary"),
    ("rl", "Consumer Discretionary"),
    ("tpr", "Consumer Discretionary"),
    ("jwn", "Consumer Discretionary"),
    ("kss", "Consumer Discretionary"),
    ("m", "Consumer Discretionary"),
    ("urbn", "Consumer Discretionary"),
    ("aeo", "Consumer Discretionary"),
    ("anf", "Consumer Discretionary"),
    ("gps", "Consumer Discretionary"),
    ("gpc", "Consumer Discretionary"),
    ("aap", "Consumer Discretionary"),
    ("azo", "Consumer Discretionary"),
    ("orly", "Consumer Discretionary"),
    ("f", "Consumer Discretionary"),
    ("gm", "Consumer Discretionary"),
    ("aptv", "Consumer Discretionary"),
    ("mga", "Consumer Discretionary"),
    ("lea", "Consumer Discretionary"),
    ("ten", "Consumer Discretionary"),
    ("lkq", "Consumer Discretionary"),
    ("pool", "Consumer Discretionary"),
    ("phm", "Consumer Discretionary"),
    ("dhi", "Consumer Discretionary"),
    ("len", "Consumer Discretionary"),
    ("nvu", "Consumer Discretionary"),
    ("mho", "Consumer Discretionary"),
    ("mdc", "Consumer Discretionary"),
    # Consumer Staples
    ("pg", "Consumer Staples"),
    ("ko", "Consumer Staples"),
    ("pep", "Consumer Staples"),
    ("cost", "Consumer Staples"),
    ("wmt", "Consumer Staples"),
    ("mo", "Consumer Staples"),
    ("pm", "Consumer Staples"),
    ("mdlz", "Consumer Staples"),
    ("cl", "Consumer Staples"),
    ("khc", "Consumer Staples"),
    ("gis", "Consumer Staples"),
    ("k", "Consumer Staples"),
    ("cpb", "Consumer Staples"),
    ("hrl", "Consumer Staples"),
    ("mkc", "Consumer Staples"),
    ("sjm", "Consumer Staples"),
    ("cag", "Consumer Staples"),
    ("ingr", "Consumer Staples"),
    ("unfi", "Consumer Staples"),
    ("fizz", "Consumer Staples"),
    ("clx", "Consumer Staples"),
    ("chd", "Consumer Staples"),
    ("spb", "Consumer Staples"),
    ("enr", "Consumer Staples"),
    ("hele", "Consumer Staples"),
    ("coty", "Consumer Staples"),
    ("el", "Consumer Staples"),
    ("ulta", "Consumer Staples"),
    ("prgo", "Consumer Staples"),
    ("kr", "Consumer Staples"),
    ("syw", "Consumer Staples"),
    ("cci", "Consumer Staples"),
    ("mktx", "Consumer Staples"),
    ("ste", "Consumer Staples"),
    ("syy", "Consumer Staples"),
    ("usfd", "Consumer Staples"),
    ("pfgc", "Consumer Staples"),
    # Energy
    ("xom", "Energy"),
    ("cvx", "Energy"),
    ("cop", "Energy"),
    ("eog", "Energy"),
    ("slb", "Energy"),
    ("pxd", "Energy"),
    ("mpc", "Energy"),
    ("vlo", "Energy"),
    ("psx", "Energy"),
    ("hes", "Energy"),
    ("hal", "Energy"),
    ("bkr", "Energy"),
    ("dvn", "Energy"),
    ("fang", "Energy"),
    ("apa", "Energy"),
    ("oxy", "Energy"),
    ("trgp", "Energy"),
    ("mplx", "Energy"),
    ("paa", "Energy"),
    ("epd", "Energy"),
    ("et", "Energy"),
    ("wmb", "Energy"),
    ("kmi", "Energy"),
    ("oke", "Energy"),
    ("lng", "Energy"),
    ("ctra", "Energy"),
    ("mtdr", "Energy"),
    ("sm", "Energy"),
    ("crc", "Energy"),
    ("pdce", "Energy"),
    ("cpg", "Energy"),
    ("pr", "Energy"),
    ("pes", "Energy"),
    # Materials
    ("lin", "Materials"),
    ("apd", "Materials"),
    ("shw", "Materials"),
    ("fcx", "Materials"),
    ("nem", "Materials"),
    ("ctva", "Materials"),
    ("mos", "Materials"),
    ("cf", "Materials"),
    ("nue", "Materials"),
    ("stld", "Materials"),
    ("cmc", "Materials"),
    ("wor", "Materials"),
    ("pkg", "Materials"),
    ("ip", "Materials"),
    ("wrk", "Materials"),
    ("gpk", "Materials"),
    ("cck", "Materials"),
    ("ball", "Materials"),
    ("alb", "Materials"),
    ("ce", "Materials"),
    ("emn", "Materials"),
    ("hun", "Materials"),
    ("fmc", "Materials"),
    ("iff", "Materials"),
    ("ppg", "Materials"),
    ("rpm", "Materials"),
    ("avnt", "Materials"),
    ("trox", "Materials"),
    ("amcr", "Materials"),
    ("gfl", "Materials"),
    ("aem", "Materials"),
    ("nwl", "Materials"),
    # Real Estate
    ("pld", "Real Estate"),
    ("amt", "Real Estate"),
    ("eqix", "Real Estate"),
    ("psa", "Real Estate"),
    ("spg", "Real Estate"),
    ("vtr", "Real Estate"),
    ("o", "Real Estate"),
    ("dlr", "Real Estate"),
    ("avb", "Real Estate"),
    ("eqr", "Real Estate"),
    ("ess", "Real Estate"),
    ("udr", "Real Estate"),
    ("maa", "Real Estate"),
    ("nnn", "Real Estate"),
    ("src", "Real Estate"),
    ("vici", "Real Estate"),
    ("glpi", "Real Estate"),
    ("eprt", "Real Estate"),
    ("adc", "Real Estate"),
    ("stag", "Real Estate"),
    ("rexr", "Real Estate"),
    ("cold", "Real Estate"),
    ("fr", "Real Estate"),
    ("egp", "Real Estate"),
    ("ofc", "Real Estate"),
    ("ctre", "Real Estate"),
    ("well", "Real Estate"),
    ("peak", "Real Estate"),
    ("hr", "Real Estate"),
    ("sbac", "Real Estate"),
    ("irm", "Real Estate"),
    ("lamr", "Real Estate"),
    ("mac", "Real Estate"),
    ("brx", "Real Estate"),
    ("roic", "Real Estate"),
    # Utilities
    ("nee", "Utilities"),
    ("duk", "Utilities"),
    ("so", "Utilities"),
    ("d", "Utilities"),
    ("exc", "Utilities"),
    ("xel", "Utilities"),
    ("ed", "Utilities"),
    ("aes", "Utilities"),
    ("wec", "Utilities"),
    ("cms", "Utilities"),
    ("ppl", "Utilities"),
    ("fe", "Utilities"),
    ("ni", "Utilities"),
    ("es", "Utilities"),
    ("dte", "Utilities"),
    ("etr", "Utilities"),
    ("evrg", "Utilities"),
    ("ava", "Utilities"),
    ("por", "Utilities"),
    ("nwe", "Utilities"),
    ("mdu", "Utilities"),
    ("lnt", "Utilities"),
    ("pnm", "Utilities"),
    ("nrg", "Utilities"),
    ("aee", "Utilities"),
    ("cnp", "Utilities"),
    ("aep", "Utilities"),
    ("sre", "Utilities"),
    ("awk", "Utilities"),
    ("awr", "Utilities"),
    ("cwt", "Utilities"),
    ("swx", "Utilities"),
    ("ugi", "Utilities"),
    ("oge", "Utilities"),
    # Communication Services
    ("googl", "Communication Services"),
    ("goog", "Communication Services"),
    ("meta", "Communication Services"),
    ("nflx", "Communication Services"),
    ("dis", "Communication Services"),
    ("cmcsa", "Communication Services"),
    ("vz", "Communication Services"),
    ("t", "Communication Services"),
    ("chtr", "Communication Services"),
    ("tmus", "Communication Services"),
    ("dish", "Communication Services"),
    ("siri", "Communication Services"),
    ("ipg", "Communication Services"),
    ("omc", "Communication Services"),
    ("foxa", "Communication Services"),
    ("fox", "Communication Services"),
    ("nwsa", "Communication Services"),
    ("nws", "Communication Services"),
    ("nyt", "Communication Services"),
    ("para", "Communication Services"),
    ("amcx", "Communication Services"),
    ("lyv", "Communication Services"),
    ("msgs", "Communication Services"),
    ("wbd", "Communication Services"),
    ("zg", "Communication Services"),
    ("z", "Communication Services"),
    ("mtch", "Communication Services"),
    ("iaci", "Communication Services"),
    ("yelp", "Communication Services"),
    ("trip", "Communication Services"),
]


def upgrade() -> None:
    # ------------------------------------------------------------------
    # atlas_stock_states_daily — add rs_state + compute_run_id
    # ------------------------------------------------------------------
    op.execute("""
        ALTER TABLE us_atlas.atlas_stock_states_daily
            ADD COLUMN IF NOT EXISTS rs_state       VARCHAR(30),
            ADD COLUMN IF NOT EXISTS compute_run_id UUID
    """)

    # ------------------------------------------------------------------
    # atlas_stock_metrics_daily — add effort_ratio_63 for volume state
    # and make instrument_id nullable (pipeline uses ticker-based access)
    # ------------------------------------------------------------------
    op.execute("""
        ALTER TABLE us_atlas.atlas_stock_metrics_daily
            ADD COLUMN IF NOT EXISTS effort_ratio_63 NUMERIC(10, 8)
    """)
    op.execute("""
        ALTER TABLE us_atlas.atlas_stock_metrics_daily
            ALTER COLUMN instrument_id DROP NOT NULL
    """)

    # ------------------------------------------------------------------
    # Seed S&P 500 universe into atlas_universe_stocks
    # ------------------------------------------------------------------
    values = ", ".join(f"('{ticker}', 'Large', TRUE, '{sector}')" for ticker, sector in _SP500)
    op.execute(
        f"INSERT INTO us_atlas.atlas_universe_stocks "  # noqa: S608 -- no user input; _SP500 is a hardcoded constant
        f"(ticker, tier, in_sp500, gics_sector) VALUES {values} "
        f"ON CONFLICT (ticker) DO UPDATE SET "
        f"gics_sector = EXCLUDED.gics_sector, in_sp500 = TRUE, tier = 'Large'"
    )

    # ------------------------------------------------------------------
    # Seed state thresholds that states.py needs but weren't in 055.
    # 059 seeded these into us_atlas already — use ON CONFLICT DO NOTHING.
    # These are listed explicitly here so the migration is self-documenting.
    # ------------------------------------------------------------------
    extra_thresholds = [
        (
            "rs_quintile_top",
            0.80,
            "rs",
            "RS pctile above which = Leader/Strong",
            "ratio",
            0.60,
            0.95,
            0.80,
        ),
        (
            "rs_quintile_bottom",
            0.20,
            "rs",
            "RS pctile below which = Laggard/Weak",
            "ratio",
            0.05,
            0.40,
            0.20,
        ),
        (
            "momentum_flat_band_pct",
            0.02,
            "momentum",
            "EMA10 within 2pct of 1.0 = Flat",
            "ratio",
            0.01,
            0.05,
            0.02,
        ),
        (
            "momentum_ema_convergence_pct",
            0.01,
            "momentum",
            "EMA10-EMA20 within 1pct = converged",
            "ratio",
            0.005,
            0.03,
            0.01,
        ),
        (
            "risk_extension_low_max_pct",
            25.0,
            "risk",
            "Extension below 25pct = Low risk",
            "pct",
            10.0,
            40.0,
            25.0,
        ),
        (
            "risk_extension_high_min_pct",
            40.0,
            "risk",
            "Extension above 40pct = High risk",
            "pct",
            25.0,
            60.0,
            40.0,
        ),
        (
            "risk_vol_ratio_low_max",
            1.0,
            "risk",
            "Vol ratio below 1.0 = Low volatility",
            "ratio",
            0.5,
            1.5,
            1.0,
        ),
        (
            "risk_vol_ratio_normal_max",
            1.25,
            "risk",
            "Vol ratio below 1.25 = Normal volatility",
            "ratio",
            1.0,
            1.75,
            1.25,
        ),
        (
            "risk_vol_ratio_high_min",
            1.6,
            "risk",
            "Vol ratio above 1.6 = High volatility",
            "ratio",
            1.25,
            2.5,
            1.6,
        ),
        (
            "volume_accumulation_expansion_min",
            1.2,
            "volume",
            "Vol expansion >= 1.2 = Accumulation",
            "ratio",
            1.0,
            1.5,
            1.2,
        ),
        (
            "volume_accumulation_effort_min",
            1.3,
            "volume",
            "Effort ratio >= 1.3 = Accumulation",
            "ratio",
            1.0,
            1.8,
            1.3,
        ),
        (
            "volume_distribution_effort_max",
            0.8,
            "volume",
            "Effort ratio <= 0.8 = Distribution",
            "ratio",
            0.5,
            1.0,
            0.8,
        ),
        (
            "volume_heavy_distribution_effort_max",
            0.6,
            "volume",
            "Effort ratio <= 0.6 = Heavy Distribution",
            "ratio",
            0.3,
            0.8,
            0.6,
        ),
    ]
    for key, val, cat, desc, units, mn, mx, dflt in extra_thresholds:
        op.execute(
            f"INSERT INTO us_atlas.atlas_thresholds "  # noqa: S608 -- no user input
            f"(threshold_key, threshold_value, category, description, methodology_section, "
            f"units, min_allowed, max_allowed, default_value) "
            f"VALUES ('{key}', {val}, '{cat}', '{desc}', NULL, '{units}', {mn}, {mx}, {dflt}) "
            f"ON CONFLICT (threshold_key) DO NOTHING"
        )


def downgrade() -> None:
    op.execute("DELETE FROM us_atlas.atlas_universe_stocks WHERE in_sp500 = TRUE")
    op.execute("""
        ALTER TABLE us_atlas.atlas_stock_metrics_daily
            DROP COLUMN IF EXISTS effort_ratio_63
    """)
    op.execute("""
        ALTER TABLE us_atlas.atlas_stock_states_daily
            DROP COLUMN IF EXISTS rs_state,
            DROP COLUMN IF EXISTS compute_run_id
    """)
