(()=>{var e={};e.id=550,e.ids=[550],e.modules={3295:e=>{"use strict";e.exports=require("next/dist/server/app-render/after-task-async-storage.external.js")},5069:(e,t,s)=>{"use strict";s.d(t,{A:()=>o});var r=s(43971);if(!process.env.ATLAS_DB_URL)throw Error("ATLAS_DB_URL is not defined. Set it in .env.local.");let a=process.env.ATLAS_DB_URL.includes("pooler.supabase.com");if(process.env.ATLAS_DB_URL.includes(":6543/"))throw Error("ATLAS_DB_URL must use session-mode pooler (port 5432), not transaction-mode (port 6543). M13 audit trail relies on sql.begin() + SET LOCAL which requires a pinned connection.");let o=(0,r.A)(process.env.ATLAS_DB_URL,{max:14,idle_timeout:10,max_lifetime:300,connect_timeout:10,prepare:!a,ssl:!!process.env.ATLAS_DB_URL.includes("sslmode=require")&&{rejectUnauthorized:!1}})},10846:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},21820:e=>{"use strict";e.exports=require("os")},22392:(e,t,s)=>{"use strict";s.r(t),s.d(t,{patchFetch:()=>h,routeModule:()=>p,serverHooks:()=>m,workAsyncStorage:()=>c,workUnitAsyncStorage:()=>_});var r={};s.r(r),s.d(r,{POST:()=>d,dynamic:()=>u});var a=s(96559),o=s(48088),i=s(37719),n=s(32190),l=s(37745);let u="force-dynamic";async function d(e){let t;try{t=await e.json()}catch{return n.NextResponse.json({error_code:"bad_json",message:"Invalid JSON body"},{status:400})}let s=Array.isArray(t.edits)?t.edits:[];if(0===s.length)return n.NextResponse.json({error_code:"no_edits",message:"No edits supplied"},{status:400});let r=await (0,l.a)(s,t.modifiedBy??"fm-panel");return n.NextResponse.json({data:r})}let p=new a.AppRouteRouteModule({definition:{kind:o.RouteKind.APP_ROUTE,page:"/api/thresholds/save/route",pathname:"/api/thresholds/save",filename:"route",bundlePath:"app/api/thresholds/save/route"},resolvedPagePath:"/home/ubuntu/atlas-os/frontend/src/app/api/thresholds/save/route.ts",nextConfigOutput:"",userland:r}),{workAsyncStorage:c,workUnitAsyncStorage:_,serverHooks:m}=p;function h(){return(0,i.patchFetch)({workAsyncStorage:c,workUnitAsyncStorage:_})}},27910:e=>{"use strict";e.exports=require("stream")},29021:e=>{"use strict";e.exports=require("fs")},29294:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-async-storage.external.js")},34631:e=>{"use strict";e.exports=require("tls")},37745:(e,t,s)=>{"use strict";s.d(t,{J:()=>o,a:()=>i});var r=s(5069);let a=e=>null==e?null:Number(e);async function o(){return(await (0,r.A)`
    SELECT threshold_key, threshold_value, category, description, units,
           min_allowed, max_allowed, default_value, last_modified_by, last_modified_at
    FROM atlas_foundation.atlas_thresholds
    WHERE is_active
    ORDER BY category, threshold_key
  `).map(e=>({key:e.threshold_key,value:Number(e.threshold_value),category:e.category??"other",description:e.description,units:e.units,min:a(e.min_allowed),max:a(e.max_allowed),default:a(e.default_value),isWeight:"lens_weight"===e.category,lastModifiedBy:e.last_modified_by,lastModifiedAt:e.last_modified_at}))}async function i(e,t="fm-panel"){let s=new Map((await (0,r.A)`
    SELECT threshold_key, min_allowed, max_allowed
    FROM atlas_foundation.atlas_thresholds WHERE is_active
  `).map(e=>[e.threshold_key,{min:a(e.min_allowed),max:a(e.max_allowed)}])),o=[],n=[];for(let a of e){let e=s.get(a.key);if(!e){n.push({key:a.key,reason:"unknown key"});continue}if(!Number.isFinite(a.value)){n.push({key:a.key,reason:"not a number"});continue}if(null!=e.min&&a.value<e.min){n.push({key:a.key,reason:`below min ${e.min}`});continue}if(null!=e.max&&a.value>e.max){n.push({key:a.key,reason:`above max ${e.max}`});continue}await (0,r.A)`
      UPDATE atlas_foundation.atlas_thresholds
      SET threshold_value = ${a.value}, last_modified_by = ${t}, last_modified_at = now()
      WHERE threshold_key = ${a.key} AND is_active
    `,o.push(a.key)}return{updated:o,rejected:n}}},44870:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},55511:e=>{"use strict";e.exports=require("crypto")},63033:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-unit-async-storage.external.js")},74998:e=>{"use strict";e.exports=require("perf_hooks")},78335:()=>{},91645:e=>{"use strict";e.exports=require("net")},96487:()=>{}};var t=require("../../../../webpack-runtime.js");t.C(e);var s=e=>t(t.s=e),r=t.X(0,[447,971,580],()=>s(22392));module.exports=r})();