"""Atlas configuration.

Single source of truth for connection settings, schema names, and v0 build
constants. Reads from environment via ``python-dotenv`` so local development
just needs a ``.env`` file at repo root.

Per architecture Section 2.4: ``ATLAS_DB_URL`` is the only connection string;
never hardcoded. Per architecture 5.6: thresholds are read from the database,
not from this file.
"""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

# Load .env from repo root if present. No-op in deployed environments where
# secrets come from the environment directly.
_REPO_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(_REPO_ROOT / ".env")


class Config:
    """Static configuration for Atlas v0.

    Read once at import time. To change DB target, set ``ATLAS_DB_URL``
    in ``.env`` or as an env var; do not edit this file.
    """

    # Database — single Supabase Postgres in v0 per prds/00_INFRA_DECISIONS.md
    DB_URL: str = os.environ.get("ATLAS_DB_URL", "")

    # Schemas — atlas writes to its own schema; reads from public.de_*
    SCHEMA_NAME: str = "atlas"
    SOURCE_SCHEMA: str = "public"

    # Universe lock — set at M1 execution time. Default to today; override via env.
    UNIVERSE_LOCK_DATE: str = os.environ.get("ATLAS_UNIVERSE_LOCK_DATE", "2026-05-06")

    # Historical scope — methodology Section 3.4 says "2014-04-01" (12y).
    # JIP's index_prices history actually starts 2016-04-07 — so v0 effective
    # scope is ~10 years (2016-04-07 to T-1). Stock OHLCV reaches 2007 but
    # RS computations need an index benchmark, which bounds us here.
    # See prds/00_INFRA_DECISIONS.md Section 11 for the v0 reality call.
    HISTORICAL_START_DATE: str = "2016-04-07"

    # Connection pool — modest defaults; raise if compute contention emerges
    POOL_SIZE: int = int(os.environ.get("ATLAS_DB_POOL_SIZE", "5"))
    MAX_OVERFLOW: int = int(os.environ.get("ATLAS_DB_MAX_OVERFLOW", "10"))

    # Slack webhook — optional. Missing webhook = warnings logged, not posted.
    SLACK_WEBHOOK_URL: str = os.environ.get("ATLAS_SLACK_WEBHOOK_URL", "")

    # Auth — Supabase JWT secret for Bearer token verification.
    # Set ATLAS_AUTH_DISABLED=true in local .env to bypass JWT checks during dev.
    SUPABASE_JWT_SECRET: str = os.environ.get("SUPABASE_JWT_SECRET", "")
    SUPABASE_JWT_AUDIENCE: str = os.environ.get("SUPABASE_JWT_AUDIENCE", "")
    SUPABASE_JWT_ISSUER: str = os.environ.get("SUPABASE_JWT_ISSUER", "")
    AUTH_DISABLED: bool = os.environ.get("ATLAS_AUTH_DISABLED", "false").lower() == "true"

    # Internal service-to-service token — used by the Next.js proxy for
    # /api/v1/intraday/* routes. Never expose to browser clients.
    ATLAS_INTERNAL_SECRET: str = os.environ.get("ATLAS_INTERNAL_SECRET", "")

    # TradingView integration — SP10 TV Signal + Report
    TV_WEBHOOK_SECRET: str = os.environ.get("TV_WEBHOOK_SECRET", "")
    TV_SESSION_ID: str = os.environ.get("TV_SESSION_ID", "")
    TV_SESSION_SIGN: str = os.environ.get("TV_SESSION_SIGN", "")
    TV_LAYOUT_ID_VS_NIFTY: str = os.environ.get("TV_LAYOUT_ID_VS_NIFTY", "")
    TV_LAYOUT_ID_VS_SECTOR: str = os.environ.get("TV_LAYOUT_ID_VS_SECTOR", "")
    TV_ACCOUNT_EMAIL: str = os.environ.get("TV_ACCOUNT_EMAIL", "")
    SIGNAL_SCREENSHOT_DIR: str = os.environ.get(
        "SIGNAL_SCREENSHOT_DIR", "/data/signals/screenshots"
    )
    SIGNAL_REPORT_BASE_URL: str = os.environ.get(
        "SIGNAL_REPORT_BASE_URL", "https://atlas.jslwealth.in/signals"
    )

    @classmethod
    def assert_db_url(cls) -> str:
        """Fail loudly if ``ATLAS_DB_URL`` is missing.

        Called by pipelines that need a live connection. Code paths that
        don't need DB (e.g., pure-math unit tests) can skip this.
        """
        if not cls.DB_URL:
            raise RuntimeError(
                "ATLAS_DB_URL is not set. Add it to .env or export it. "
                "Format: postgresql+psycopg2://user:pass@host:5432/dbname"
            )
        return cls.DB_URL
