"""Atlas configuration.

Single source of truth for connection settings, schema names, and v0 build
constants. Reads from environment via ``python-dotenv`` so local development
just needs a ``.env`` file at repo root.

Per architecture Section 2.4: ``ATLAS_DB_URL`` is the only connection string;
never hardcoded. Per architecture 5.6: thresholds are read from the database,
not from this file.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from dotenv import load_dotenv

# Load .env from repo root if present. No-op in deployed environments where
# secrets come from the environment directly.
_REPO_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(_REPO_ROOT / ".env")


class Config:
    """Static configuration for Atlas v0.

    Read once at import time. To change DB target, set ``ATLAS_DB_URL``
    in ``.env`` or as an env var; do not edit this file.
    """

    # Database — the single Supabase Postgres (schema atlas_foundation).
    DB_URL: str = os.environ.get("ATLAS_DB_URL", "")

    # The one and only data schema. There is no source schema — atlas ingests
    # its own data (see scripts/foundation/).
    SCHEMA_NAME: str = "atlas_foundation"

    UNIVERSE_LOCK_DATE: str = os.environ.get("ATLAS_UNIVERSE_LOCK_DATE", "2026-05-06")

    # Historical scope is bounded by index-benchmark availability (RS needs an
    # index): index history starts 2016-04-07, so effective scope is ~10y to T-1.
    HISTORICAL_START_DATE: str = "2016-04-07"

    # Connection pool — modest defaults; raise if compute contention emerges
    POOL_SIZE: int = int(os.environ.get("ATLAS_DB_POOL_SIZE", "5"))
    MAX_OVERFLOW: int = int(os.environ.get("ATLAS_DB_MAX_OVERFLOW", "10"))

    # Slack webhook — optional. Missing webhook = warnings logged, not posted.
    SLACK_WEBHOOK_URL: str = os.environ.get("ATLAS_SLACK_WEBHOOK_URL", "")

    # Auth — Supabase JWT secret for Bearer token verification.
    # Set ATLAS_AUTH_DISABLED=true in local .env to bypass JWT checks during dev.
    SUPABASE_JWT_SECRET: str = os.environ.get("SUPABASE_JWT_SECRET", "")
    SUPABASE_JWT_AUDIENCE: str = os.environ.get("SUPABASE_JWT_AUDIENCE", "")
    SUPABASE_JWT_ISSUER: str = os.environ.get("SUPABASE_JWT_ISSUER", "")
    AUTH_DISABLED: bool = os.environ.get("ATLAS_AUTH_DISABLED", "false").lower() == "true"

    # OpenBB BYO Copilot — SP03. Empty = dev mode (auth bypassed).
    OPENBB_BACKEND_API_KEY: str = os.environ.get("OPENBB_BACKEND_API_KEY", "")

    # TradingView integration — SP10 TV Signal + Report
    TV_WEBHOOK_SECRET: str = os.environ.get("TV_WEBHOOK_SECRET", "")
    TV_SESSION_ID: str = os.environ.get("TV_SESSION_ID", "")
    TV_SESSION_SIGN: str = os.environ.get("TV_SESSION_SIGN", "")
    TV_LAYOUT_ID_VS_NIFTY: str = os.environ.get("TV_LAYOUT_ID_VS_NIFTY", "")
    TV_LAYOUT_ID_VS_SECTOR: str = os.environ.get("TV_LAYOUT_ID_VS_SECTOR", "")
    TV_ACCOUNT_EMAIL: str = os.environ.get("TV_ACCOUNT_EMAIL", "")
    SIGNAL_SCREENSHOT_DIR: str = os.environ.get(
        "SIGNAL_SCREENSHOT_DIR", "/data/signals/screenshots"
    )
    SIGNAL_REPORT_BASE_URL: str = os.environ.get(
        "SIGNAL_REPORT_BASE_URL", "https://atlas.jslwealth.in/signals"
    )

    @classmethod
    def assert_db_url(cls) -> str:
        """Fail loudly if ``ATLAS_DB_URL`` is missing.

        Called by pipelines that need a live connection. Code paths that
        don't need DB (e.g., pure-math unit tests) can skip this.
        """
        if not cls.DB_URL:
            raise RuntimeError(
                "ATLAS_DB_URL is not set. Add it to .env or export it. "
                "Format: postgresql+psycopg2://user:pass@host:5432/dbname"
            )
        return cls.DB_URL


@dataclass(frozen=True)
class MarketConfig:
    """The fixed identity of one market: where it lives and how its trading day is anchored.

    One schema per market, zero cross-schema references (ADR-0006). Everything here is a
    structural fact of the market or of our storage — never a methodology number; those
    live in ``<schema>.atlas_thresholds``.
    """

    market: str  # "india" | "us"
    schema: str  # "atlas_foundation" | "atlas_global"
    timezone: str  # "Asia/Kolkata" | "America/New_York" — the get_engine() session tz
    close_hour: int  # local hour after which the day is a complete EOD (India 16, US 17)
    # "NIFTY 50" (index_prices row) | "SPY" (ohlcv_daily row) — a session exists iff this
    # instrument has a bar for the date (membership-by-presence; no holiday tables).
    calendar_anchor: str
    currency: str  # "INR" | "USD"
    history_start: str  # "2016-04-07" | "2016-01-04" — first session of ingested history


MARKETS: dict[str, MarketConfig] = {
    "india": MarketConfig(
        market="india",
        schema=Config.SCHEMA_NAME,
        timezone="Asia/Kolkata",
        close_hour=16,
        calendar_anchor="NIFTY 50",
        currency="INR",
        history_start=Config.HISTORICAL_START_DATE,
    ),
    "us": MarketConfig(
        market="us",
        schema="atlas_global",
        timezone="America/New_York",
        close_hour=17,
        calendar_anchor="SPY",
        currency="USD",
        history_start="2016-01-04",
    ),
}
