(()=>{var e={};e.id=4878,e.ids=[4878],e.modules={3295:e=>{"use strict";e.exports=require("next/dist/server/app-render/after-task-async-storage.external.js")},5069:(e,t,r)=>{"use strict";r.d(t,{A:()=>i});var s=r(43971);if(!process.env.ATLAS_DB_URL)throw Error("ATLAS_DB_URL is not defined. Set it in .env.local.");let o=process.env.ATLAS_DB_URL.includes("pooler.supabase.com");if(process.env.ATLAS_DB_URL.includes(":6543/"))throw Error("ATLAS_DB_URL must use session-mode pooler (port 5432), not transaction-mode (port 6543). M13 audit trail relies on sql.begin() + SET LOCAL which requires a pinned connection.");let i=(0,s.A)(process.env.ATLAS_DB_URL,{max:14,idle_timeout:10,max_lifetime:300,connect_timeout:10,prepare:!o,ssl:!!process.env.ATLAS_DB_URL.includes("sslmode=require")&&{rejectUnauthorized:!1}})},10846:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},21820:e=>{"use strict";e.exports=require("os")},27910:e=>{"use strict";e.exports=require("stream")},29021:e=>{"use strict";e.exports=require("fs")},29294:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-async-storage.external.js")},34631:e=>{"use strict";e.exports=require("tls")},44870:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},55511:e=>{"use strict";e.exports=require("crypto")},63033:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-unit-async-storage.external.js")},74998:e=>{"use strict";e.exports=require("perf_hooks")},78335:()=>{},91645:e=>{"use strict";e.exports=require("net")},92706:(e,t,r)=>{"use strict";r.r(t),r.d(t,{patchFetch:()=>v,routeModule:()=>d,serverHooks:()=>x,workAsyncStorage:()=>l,workUnitAsyncStorage:()=>_});var s={};r.r(s),r.d(s,{GET:()=>u,dynamic:()=>p});var o=r(96559),i=r(48088),a=r(37719),n=r(32190),c=r(5069);let p="force-dynamic";async function u(){let e=await (0,c.A)`
    SELECT
      sector,
      ppc_count,
      npc_count,
      total_tradeable,
      pivot_balance::text   AS pivot_balance,
      stage2_count,
      stage2_pct::text      AS stage2_pct,
      avg_ppc_conviction::text AS avg_ppc_conviction,
      action_alert_count
    FROM atlas.atlas_cts_sector_pivot_daily
    WHERE date = (SELECT MAX(date) FROM atlas.atlas_cts_sector_pivot_daily)
    ORDER BY COALESCE(pivot_balance, -99) DESC
  `;return n.NextResponse.json({rows:e,as_of:new Date().toISOString()})}let d=new o.AppRouteRouteModule({definition:{kind:i.RouteKind.APP_ROUTE,page:"/api/cts/sectors/route",pathname:"/api/cts/sectors",filename:"route",bundlePath:"app/api/cts/sectors/route"},resolvedPagePath:"/home/ubuntu/atlas-os/frontend/src/app/api/cts/sectors/route.ts",nextConfigOutput:"",userland:s}),{workAsyncStorage:l,workUnitAsyncStorage:_,serverHooks:x}=d;function v(){return(0,a.patchFetch)({workAsyncStorage:l,workUnitAsyncStorage:_})}},96487:()=>{}};var t=require("../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),s=t.X(0,[4447,3971,580],()=>r(92706));module.exports=s})();